Repository iNavFlight/inav-configurator, pull requests merged in 2019-03, with the labels that each got.

#721 fix compilation on windows
  package.json
Labels: Enhancement/New feature

#696 Add MAP_SCALE and MAP_REFERENCE elements
  _locales/en/messages.json
  tabs/osd.js
Labels: Don't merge

#728 Add missing LPS25H baro hardware entry
  js/fc.js
Labels: Bug
