Repository iNavFlight/inav-configurator, pull requests merged in 2019-02, with the labels that each got.

#694 Fix saving OSD alarms from GUI
  tabs/osd.js
Labels: Bug

#653 Remove Configurator support for 1.6 and 1.5
  js/fc.js
  js/msp/MSPHelper.js
  js/periodicStatusUpdater.js
  js/tasks.js
  tabs/configuration.html
  tabs/configuration.js
  tabs/failsafe.html
  tabs/failsafe.js
  tabs/onboard_logging.js
  tabs/osd.js
  tabs/pid_tuning.html
  tabs/pid_tuning.js
  tabs/sensors.js
Labels: Refactoring

#628 New mixer inputs for stabilized axises
  js/fc.js
Labels: Ready to merge
