Repository iNavFlight/inav-configurator, pull requests merged in 2022-05, with the labels that each got.

#1475 Enhance mAh Used OSD Element
  _locales/en/messages.json
  resources/osd/bold.mcm
  resources/osd/bold.png
  resources/osd/bold/211.png
  resources/osd/clarity.mcm
  resources/osd/clarity.png
  resources/osd/clarity/211.png
  resources/osd/clarity_medium.mcm
  resources/osd/clarity_medium.png
  resources/osd/clarity_medium/211.png
  resources/osd/default.mcm
  resources/osd/default.png
  resources/osd/default/211.png
  resources/osd/iNav character map.md
  resources/osd/impact.mcm
  resources/osd/impact.png
  resources/osd/impact/211.png
  resources/osd/impact_mini.mcm
  resources/osd/impact_mini.png
  resources/osd/impact_mini/211.png
  resources/osd/large.mcm
  resources/osd/large.png
  resources/osd/large/211.png
  resources/osd/vision.mcm
  resources/osd/vision.png
  resources/osd/vision/211.png
  tabs/osd.html
  tabs/osd.js
Labels: Enhancement/New feature, Ready to merge, Font change

#1508 Added idle delay to Advanced Tuning
  _locales/en/messages.json
  tabs/advanced_tuning.html
Labels: Ready to merge

#1511 Set default failsafe procedure on MR to DROP
  js/defaults_dialog.js
Labels: Release Notes

#1507 Moved font select/upload box
  tabs/osd.js
Labels: Ready to merge

#1514 Increase Logic Conditions to 64
  js/logicConditionsCollection.js
Labels: Ready to merge

#1513 PID sliders
  _locales/en/messages.json
  gulpfile.js
  js/helpers.js
  main.css
  package-lock.json
  src/css/tabs/pid_tuning.css
  tabs/pid_tuning.html
  tabs/pid_tuning.js
Labels: Release Notes

#1515 Added Fixed Wing TPA Time Constant to in flight adjustments
  _locales/en/messages.json
  tabs/adjustments.html
  tabs/adjustments.js
  tabs/osd.js
  tabs/pid_tuning.html
Labels: Ready to merge

#1519 Move the 3D config to Outputs tab
  tabs/configuration.html
  tabs/configuration.js
  tabs/outputs.html
  tabs/outputs.js
Labels: Release Notes

#1529 add new requirement to make chrome_crashpad_handler executable
  README.md
Labels: Release Notes
